name: menoti
description: "Notification Handler"
version: 1.0.0
homepage: "https://github.com/SanketKudale/Menoti"

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  plugin_platform_interface: ^2.0.2
  location: ^7.0.1
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: